FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt

# RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir streamlit requests

RUN apt-get update -y && apt-get install -y curl

COPY ui.py /app/ui.py

EXPOSE 8501

CMD ["streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
